#!/usr/bin/with-contenv bash

echo "Starting openvpn service via s6 overlay"

# Variable checks
if [ -z "$CONNECTION_PORT" ]; then
    echo "\$CONNECTION_PORT is not defined or is set to '', exiting"
    exit 1
fi

case $CONNECTION_PORT in
    ''|*[!0-9]*)
        echo "\$CONNECTION_PORT is not a number, exiting"
        exit 2
        ;;
    *) ;;
esac

if [ "$CONNECTION_PORT" -gt "65535" ]; then
    echo "\$CONNECTION_PORT is greater than the maximum (65535), exiting"
    exit 3
fi

case $FORWARDING_PORT in
    ''|*[!0-9]*)
        echo "\$FORWARDING_PORT is not a number, exiting"
        exit 4
        ;;
    *) ;;
esac

if [[ "$FORWARDING_PORT" != "0" ]] ; then
    if [[ "$FORWARDING_PORT" -lt "30000" || "$FORWARDING_PORT" -gt "65535" ]] ; then
        echo "\$FORWARDING_PORT is outside the allowed range of 30000-65535, exiting"
        exit 5
    fi
fi


# VPN configs

# Create credentials file
# Cryptostorm doesn't care what password you use so we use 'foo'
printf '%s\nfoo' "$CRYPTOSTORM_USERNAME" > /ovpn-credentials

# Remove group and other permissions (prevents an openvpn log warning)
chmod go-wrx /ovpn-credentials

# Change all configs to use the specified port
find /ovpn-configs -type f -exec sed -i "s/443/$CONNECTION_PORT/g" {} \;

# Create /dev/net/tun
mkdir -p /dev/net
if [ ! -f /dev/net/tun ]; then
    mknod /dev/net/tun c 10 200
    chmod 600 /dev/net/tun
fi

# Capture initial IP for the killswitch
curl -s api.ipify.org > /initial-ip

# Start openvpn (requires NET_ADMIN)
openvpn --client --auth-user-pass /ovpn-credentials --config "/ovpn-configs/$CRYPTOSTORM_CONFIG_FILE" 2>&1

